In [ ]:
print ("Hello")

message= "Hello Lovely Word"

print (message)

100*(1+5/100)**7



Hello
Hello Lovely Word


140.71004226562505

In [15]:


v1 = 1/51*51
v2 = 1/49*49

print (v1)
print (v2)

1.0
0.9999999999999999


In [24]:
large = 100000000

print(f"A thousand times large is {large:g}")

A thousand times large is 1e+08


In [ ]:

numero=0
for m in range(11):
    numero= numero + m

print(numero)
numero=0
i=0
while i<11:
    numero=numero+i
    i=i+1
print(numero)






     

55
55


In [21]:
def holi(palabra):
    if palabra=="filipa":
        return("10/10")
    else :
        return("vaya mierda")

palabra="filipa"

print(holi(palabra))
    

10/10


In [23]:

def suma (numero):
    sum=0
    for i in range(numero+1):
        sum=sum+i
    return (sum)


print(suma(10))

55


In [29]:
from math import pi
print(pi)

def area_circulo(radio):
    return pi*radio**2,2*pi*radio

print(area_circulo(10))

3.141592653589793
(314.1592653589793, 62.83185307179586)


In [31]:
def interest (capital,years):
    if capital<=1000:
        return capital*(1+0.05)**years
    elif 1000<capital<=10000:
        return capital*(1+0.06)**years
    else:
        return capital*(1+0.08)**years

print(interest(1000,7))
print(interest(10000,7))
print(interest(100000,7))

    

1407.1004226562504
15036.302589913606
171382.4268779521


In [1]:


def amount_en_lista(capital,years):
    numero=0
    lista1=[]
    for i in range(years+1):
        numero= capital*(1+0.05)**i
        lista1.append(numero)
    return lista1

amount_en_lista(100,10)

[100.0,
 105.0,
 110.25,
 115.76250000000002,
 121.55062500000003,
 127.62815625000003,
 134.00956406250003,
 140.71004226562505,
 147.7455443789063,
 155.13282159785163,
 162.8894626777442]

In [ ]:
Numpy 

In [5]:

import os 
import scipy
import numpy as np 
import matplotlib.pyplot as plt

root = np.sqrt(2)
print(root)

print(np.exp(2))

vec = np.array([1,2,3,4,5])
print(vec)

mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mat)

B= np.array([[[1,2],[3,4]],[[5,6],[7,8]]],dtype=complex)
print(B)

print(B.shape)

B.dtype

v= np.arange(0,10,1)
print(v)

v= np.arange(-1,1,0.1)
print(v)

v= np.linspace(0,10,11)
print(v)




1.4142135623730951
7.38905609893065
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[1.+0.j 2.+0.j]
  [3.+0.j 4.+0.j]]

 [[5.+0.j 6.+0.j]
  [7.+0.j 8.+0.j]]]
(2, 2, 2)
[0 1 2 3 4 5 6 7 8 9]
[-1.00000000e+00 -9.00000000e-01 -8.00000000e-01 -7.00000000e-01
 -6.00000000e-01 -5.00000000e-01 -4.00000000e-01 -3.00000000e-01
 -2.00000000e-01 -1.00000000e-01 -2.22044605e-16  1.00000000e-01
  2.00000000e-01  3.00000000e-01  4.00000000e-01  5.00000000e-01
  6.00000000e-01  7.00000000e-01  8.00000000e-01  9.00000000e-01]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [ ]:
A= np.zeros(10)
print(A)

A= np.zeros([2,2,2])
print(A)

Identity = np.eye(4)
Diagonal = np.diag([7,8,1])
Random = np.random.rand(5,5)

print(Identity)
print(Diagonal)
print(Random)

print(Random[0,0])
print("hola")

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[7 0 0]
 [0 8 0]
 [0 0 1]]
[[0.22400427 0.30281928 0.91664642 0.7723861  0.00923398]
 [0.18857746 0.16571631 0.24695323 0.41511332 0.68812704]
 [0.00982522 0.81622505 0.01025796 0.57510688 0.24973391]
 [0.72984306 0.86646326 0.5776258  0.25501341 0.46279114]
 [0.88784095 0.70286628 0.47078739 0.48439091 0.35181592]]


In [25]:
import numpy as np  # Asegura importar numpy

B = []  # Lista vacía

for i in np.arange(0, 2*np.pi, 0.01):  # Usar np.arange() para valores decimales
    a = np.sin(i)  # Usar np.sin() en lugar de sen()
    B.append(a)  # Usar append() correctamente

B = np.array(B)  # Convertir la lista en un array de NumPy

print(B)

[ 0.          0.00999983  0.01999867  0.0299955   0.03998933  0.04997917
  0.05996401  0.06994285  0.07991469  0.08987855  0.09983342  0.1097783
  0.11971221  0.12963414  0.13954311  0.14943813  0.15931821  0.16918235
  0.17902957  0.18885889  0.19866933  0.2084599   0.21822962  0.22797752
  0.23770263  0.24740396  0.25708055  0.26673144  0.27635565  0.28595223
  0.29552021  0.30505864  0.31456656  0.32404303  0.33348709  0.34289781
  0.35227423  0.36161543  0.37092047  0.38018842  0.38941834  0.39860933
  0.40776045  0.4168708   0.42593947  0.43496553  0.44394811  0.45288629
  0.46177918  0.47062589  0.47942554  0.48817725  0.49688014  0.50553334
  0.51413599  0.52268723  0.5311862   0.53963205  0.54802394  0.55636102
  0.56464247  0.57286746  0.58103516  0.58914476  0.59719544  0.60518641
  0.61311685  0.62098599  0.62879302  0.63653718  0.64421769  0.65183377
  0.65938467  0.66686964  0.67428791  0.68163876  0.68892145  0.69613524
  0.70327942  0.71035327  0.71735609  0.72428717  0.

In [ ]:
MatrizZ = np.array([[2,3,2,4],[4,1,0,17],[24,0,-1,-3],[4,2,14,2]])

for j in  range(0,4,1):
   for i in  range(0,4,1):
        if i != j:
            MatrizZ[i,j] = 0
        if j == 0 and i == 3 or j == 3 and i == 0:
            MatrizZ[i,j] = 4
    

    f

    

print(MatrizZ)
            



[[ 2  0  0  4]
 [ 0  1  0  0]
 [ 0  0 -1  0]
 [ 4  0  0  2]]
