In [ ]:
print ("Hello")

message= "Hello Lovely Word"

print (message)

100*(1+5/100)**7



Hello
Hello Lovely Word


140.71004226562505

In [15]:


v1 = 1/51*51
v2 = 1/49*49

print (v1)
print (v2)

1.0
0.9999999999999999


In [24]:
large = 100000000

print(f"A thousand times large is {large:g}")

A thousand times large is 1e+08


In [ ]:

numero=0
for m in range(11):
    numero= numero + m

print(numero)
numero=0
i=0
while i<11:
    numero=numero+i
    i=i+1
print(numero)






     

55
55


In [21]:
def holi(palabra):
    if palabra=="filipa":
        return("10/10")
    else :
        return("vaya mierda")

palabra="filipa"

print(holi(palabra))
    

10/10


In [23]:

def suma (numero):
    sum=0
    for i in range(numero+1):
        sum=sum+i
    return (sum)


print(suma(10))

55


In [29]:
from math import pi
print(pi)

def area_circulo(radio):
    return pi*radio**2,2*pi*radio

print(area_circulo(10))

3.141592653589793
(314.1592653589793, 62.83185307179586)


In [31]:
def interest (capital,years):
    if capital<=1000:
        return capital*(1+0.05)**years
    elif 1000<capital<=10000:
        return capital*(1+0.06)**years
    else:
        return capital*(1+0.08)**years

print(interest(1000,7))
print(interest(10000,7))
print(interest(100000,7))

    

1407.1004226562504
15036.302589913606
171382.4268779521


In [1]:


def amount_en_lista(capital,years):
    numero=0
    lista1=[]
    for i in range(years+1):
        numero= capital*(1+0.05)**i
        lista1.append(numero)
    return lista1

amount_en_lista(100,10)

[100.0,
 105.0,
 110.25,
 115.76250000000002,
 121.55062500000003,
 127.62815625000003,
 134.00956406250003,
 140.71004226562505,
 147.7455443789063,
 155.13282159785163,
 162.8894626777442]

In [ ]:
Numpy 

In [3]:

import os 
import scipy
import numpy as np 
import matplotlib.pyplot as plt

root = np.sqrt(2)
print(root)

print(np.exp(2))

vec = np.array([1,2,3,4,5])
print(vec)

mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mat)

B= np.array([[[1,2],[3,4]],[[5,6],[7,8]]],dtype=complex)
print(B)

print(B.shape)

B.dtype

v= np.arange(0,10,1)
print(v)

v= np.arange(-1,1,0.1)
print(v)

v= np.linspace(0,10,11)
print(v)




1.4142135623730951
7.38905609893065
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[1.+0.j 2.+0.j]
  [3.+0.j 4.+0.j]]

 [[5.+0.j 6.+0.j]
  [7.+0.j 8.+0.j]]]
(2, 2, 2)
[0 1 2 3 4 5 6 7 8 9]
[-1.00000000e+00 -9.00000000e-01 -8.00000000e-01 -7.00000000e-01
 -6.00000000e-01 -5.00000000e-01 -4.00000000e-01 -3.00000000e-01
 -2.00000000e-01 -1.00000000e-01 -2.22044605e-16  1.00000000e-01
  2.00000000e-01  3.00000000e-01  4.00000000e-01  5.00000000e-01
  6.00000000e-01  7.00000000e-01  8.00000000e-01  9.00000000e-01]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [ ]:
A= np.zeros(10)
print(A)

A= np.zeros([2,2,2])
print(A)

Identity = np.eye(4)
Diagonal = np.diag([7,8,1])
Random = np.random.rand(5,5)

print(Identity)
print(Diagonal)
print(Random)

print(Random[0,0])

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[7 0 0]
 [0 8 0]
 [0 0 1]]
[[0.22400427 0.30281928 0.91664642 0.7723861  0.00923398]
 [0.18857746 0.16571631 0.24695323 0.41511332 0.68812704]
 [0.00982522 0.81622505 0.01025796 0.57510688 0.24973391]
 [0.72984306 0.86646326 0.5776258  0.25501341 0.46279114]
 [0.88784095 0.70286628 0.47078739 0.48439091 0.35181592]]
